#pragma once

#include <ntddk.h>

extern const GUID GUID_DEVINTERFACE_PS5169;

#define IOCTL_PS5169_CONFIGURE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define PS5169_CONFIG_ATTACH_NONE 0x00
#define PS5169_CONFIG_ATTACH_UFP  0x01
#define PS5169_CONFIG_ATTACH_DFP  0x02

typedef struct _PS5169_CONFIG_REQUEST
{
    UCHAR Attach;
    UCHAR Orientation;
} PS5169_CONFIG_REQUEST, *PPS5169_CONFIG_REQUEST;