#pragma once

#include <ntddk.h>

extern const GUID GUID_DEVINTERFACE_SM5714_BATTERY;

#define IOCTL_SM5714_BATTERY_SET_EXTERNAL_POWER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_WRITE_DATA)

typedef struct _SM5714_BATTERY_POWER_REQUEST
{
	ULONG ExternalPowerOnline;
} SM5714_BATTERY_POWER_REQUEST, *PSM5714_BATTERY_POWER_REQUEST;